import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
// import Navbar from '../components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-sky-100 via-white to-sky-200 min-h-screen font-sans text-white">
        {/* <Navbar /> */}

        <main className="flex items-center justify-center min-h-[calc(100vh-80px)] p-4">
          <div className="w-full max-w-5xl rounded-[2rem] bg-white/10 border border-white/30 backdrop-blur-3xl shadow-[0_8px_32px_0_rgba(31,38,135,0.37)] p-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}